/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sasclient.swing;

import java.awt.Font;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

import br.sasclient.entity.Ocorrencia;
import br.sasclient.entity.Tela;
import br.sasclient.swing.msg.JPanelConfirmar;
import br.sasclient.util.Java8Base64Image;

/**
 *
 * @author wally
 */
public class TelaJD extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6331140489114267146L;
	/**
	 * 
	 */
    private Tela tela;
    private int codigo;
    private Ocorrencia ocorrencia;
    private Monitoramento monitoramento;
    
    
    /**
     * Creates new form TelaJD
     * @param titulo
     * @param tela
     */
    public TelaJD(Tela tela, int index, Monitoramento monitoramento) {
        this.tela = tela;
        setCodigo(index);
        this.monitoramento = monitoramento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_foto = new javax.swing.JPanel();
        jl_foto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jl_nome = new javax.swing.JLabel();
        jl_nome.setFont(new Font("Tahoma", Font.PLAIN, 9));
        jl_nome.setHorizontalAlignment(SwingConstants.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jp_fotoLayout = new javax.swing.GroupLayout(jp_foto);
        jp_foto.setLayout(jp_fotoLayout);
        jp_fotoLayout.setHorizontalGroup(
            jp_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jp_fotoLayout.setVerticalGroup(
            jp_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel1.add(jp_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jl_nome.setText("jLabel1");
        jl_nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jl_nomeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 80, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));
        
        Image img = new Java8Base64Image().decoder80(tela.getFoto(), tela.getColaborador());
        
        jl_foto.setIcon(new ImageIcon(img));
        jl_nome.setText(tela.getPrefixo() + " " + getSplit(tela));
    }// </editor-fold>//GEN-END:initComponents

    private void jl_nomeMousePressed(java.awt.event.MouseEvent evt) {

		JPanelConfirmar p = new JPanelConfirmar(tela.getCodigo_colaborador(), this);
		p.setVisible(true);
		new Thread() {
			public void run() {
				while (p.isVisible()) {
				}
				if(p.confirmacao() == 1) {
					new Monitoramento().getClickTela(tela.getCodigo_colaborador(), getCodigo());
			        setVisible(false);
				} else if(p.confirmacao() == 2) {
					monitoramento.setOcorrenciaSelected(ocorrencia, tela);
				}
			};
		}.start();    	
    	
    }//GEN-LAST:event_jl_nomeMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_foto;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JPanel jp_foto;
    // End of variables declaration//GEN-END:variables

	
	private String getSplit(Tela t) {
		String nome[];
		
		nome = t.getColaborador().split(" ");
		
		return nome[0];
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public javax.swing.JLabel getJl_nome() {
		return jl_nome;
	}

	public void setJl_nome(javax.swing.JLabel jl_nome) {
		this.jl_nome = jl_nome;
	}
	
	public void setOcorrencia(Ocorrencia ocorrencia) {
		this.ocorrencia = ocorrencia;
		monitoramento.setOcorrenciaSelected(ocorrencia, tela);
	}
}
